#!/usr/bin/env bash
set -x

# DO NOT EDIT THIS FILE BY HAND -- FILE IS SYNCHRONIZED REGULARLY

# Available environment variables
#
# BUILD_OPTS
# REPOSITORY
# VERSION
# VERSION_AWX
# RELEASE_OPENSTACK
# RELEASE_LUMINOUS

# Set default values

BUILD_OPTS=${BUILD_OPTS:-}
CREATED=$(date --rfc-3339=ns)
REVISION=$(git rev-parse --short HEAD)
VERSION=${VERSION:-latest}

docker build \
    --build-arg "VERSION=$VERSION" \
    --build-arg "VERSION_AWX=$VERSION_AWX" \
    --build-arg "RELEASE_CEPH=$RELEASE_CEPH" \
    --build-arg "RELEASE_OPENSTACK=$RELEASE_OPENSTACK" \
    --label "org.opencontainers.image.created=$CREATED" \
    --label "org.opencontainers.image.documentation=https://docs.osism.de" \
    --label "org.opencontainers.image.licenses=ASL 2.0" \
    --label "org.opencontainers.image.revision=$REVISION" \
    --label "org.opencontainers.image.source=https://github.com/osism/docker-manager" \
    --label "org.opencontainers.image.title=kolla-ansible" \
    --label "org.opencontainers.image.url=https://www.osism.de" \
    --label "org.opencontainers.image.vendor=Betacloud Solutions GmbH" \
    --label "org.opencontainers.image.version=$VERSION" \
    --squash \
    --no-cache \
    --tag "$REPOSITORY:$VERSION" \
    $BUILD_OPTS .
