#!/usr/bin/env bash
set -x

# Available environment variables
#
# CEPH_VERSION
# DOCKER_REGISTRY
# OPENSTACK_VERSION
# REPOSITORY

# Set default values

CEPH_VERSION=${CEPH_VERSION:-nautilus}
DOCKER_REGISTRY=${DOCKER_REGISTRY:-quay.io}
OPENSTACK_VERSION=${OPENSTACK_VERSION:-train}

VERSION="$CEPH_VERSION-$OPENSTACK_VERSION"


if [[ -n $DOCKER_REGISTRY ]]; then
    REPOSITORY="$DOCKER_REGISTRY/$REPOSITORY"
fi


docker push "$REPOSITORY:$VERSION"
docker rmi "$REPOSITORY:$VERSION"
